version: '3'

networks:
  prometheus:
    driver: overlay

services:

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
    volumes:
      - '/sys:/host/sys'
      - '/:/rootfs'
      - '/proc:/host/proc'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns)($$|/)"'
    deploy:
      mode: global
    networks:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    networks:
      - prometheus

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - prometheus

  cadvisor:
    image: google/cadvisor:latest
    deploy:
      mode: global
    ports:
      - '8080:8080'
    volumes:
      - '/:/rootfs'
      - '/var/run:/var/run'
      - '/sys:/host/sys'
      - '/var/lib/docker:/var/lib/docker'
    networks:
      - prometheus

  engine-proxy:
    image: basi/socat:latest
    deploy:
      mode: global
    ports:
      - 4998:4999
    networks:
      - prometheus
